[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/:page.html"
  to = "/:page"
  status = 301
  force = true

[[redirects]]
  from = "/:page"
  to = "/:page.html"
  status = 200
